spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db
        username: postgres
        password: KarolK123@
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            database-platform: org.hibernate.dialect.PostgreSQLDialect
